# Site settings
author: B. T. Leane
title: Bones and Code
header-img: img/home-bg.png
email: barbleane@outlook.com
copyright_name: B. T. Leane
description: > # this means to ignore newlines until "baseurl:"
  Science geek learning to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bonemama

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
